cloud_to_normals:
  ros__parameters:
    use_sim_time: true
    source_topic: /point_cloud_from_depth
    dest_topic: /normals

    normal_radius: 0.1 #m
    omp_enable: true

    integral_image:
      # effective only for organized point clouds
      enable: false
      # (0) COVARIANCE_MATRIX
      # (1) AVERAGE_3D_GRADIENT
      # (2) AVERAGE_DEPTH_CHANGE
      # (3) SIMPLE_3D_GRADIENT
      method: 3
      max_depth_change_factor: 0.05
      depth_dependent_smoothing: true
      normal_smoothing_size: 20.0